In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 데이터

In [2]:
file_path = "./data/"
df_kp20 = pd.read_csv(f"{file_path}KP2020.csv", encoding="cp949")
df_kp21 = pd.read_csv(f"{file_path}KP2021.csv", encoding="cp949")
df_npa20 = pd.read_csv(f"{file_path}NPA2020.csv", encoding="cp949")

## KP 데이터

변수 정리
   
RECV_DEPT_NM : 접수 부서 이름   
RECV_CPLT_DM : 접수 완료 날짜, 시간   
NPA_CL : 경찰철 코드   
EVT_STAT_CD	: 사건 상태 코드   
EVT_CL_CD : 사건 종별 코드   
RPTER_SEX : 신고자 성별   
HPPN_PNU_ADDR : 발생 주소   
HPPN_X : 위도   
HPPN_Y : 경도   
SME_EVT_YN : 동일 사건 여부

In [3]:
df_kp20.shape

(77077, 10)

In [4]:
df_kp20['RECV_DEPT_NM'].value_counts()

충남청         41814
대전청         34600
2지구대(충남)       95
대전역지구대         89
남대전지구대         70
대전동부           64
서대전지구대         60
대전둔산           55
대전유성           48
대전중부           47
대전서부           47
대전대덕           34
대전파출소          15
세종로파출소         14
세종             14
세종청            11
Name: RECV_DEPT_NM, dtype: int64

In [5]:
df_kp20['NPA_CL'].value_counts()

19    38810
13    34763
31     2753
15      215
18      156
8       109
20       61
21       38
11       32
9        29
16       22
17       22
23       18
22       18
10       11
24        8
12        8
14        4
Name: NPA_CL, dtype: int64

In [6]:
df_kp20.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN

In [7]:
df_kp20.tail()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
77072,충남청,20/12/31 01:18:16.000000000,19,10,302,2.0,충청남도 보령시 주교면 주교리(행정:주교면) 191-6,126.571002,36.387791,NaN
77073,충남청,20/12/31 01:17:45.000000000,19,10,501,3.0,NaN,NaN,NaN,NaN
77074,충남청,20/12/31 00:13:50.000000000,19,10,604,3.0,충청남도 아산시 온천동(행정:온양1동) 1498,127.000391,36.788411,NaN
77075,대전청,20/12/31 00:49:29.000000000,13,10,302,2.0,대전광역시 서구 갈마동(행정:갈마2동) 975,127.373351,36.348051,Y
77076,대전청,20/12/31 00:49:06.000000000,13,10,601,3.0,NaN,NaN,NaN,NaN

In [8]:
df_kp20.describe()

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_X,HPPN_Y
count,77077.000000,77077.000000,77077.000000,74658.000000,60313.000000,60313.000000
mean,16.686923,9.993721,446.935779,1.727290,127.198959,36.488481
std,4.042848,0.169827,146.713005,0.809894,0.801378,0.776456
min,8.000000,3.000000,104.000000,1.000000,36.301667,33.491534
25%,13.000000,10.000000,307.000000,1.000000,127.112222,36.341685
50%,19.000000,10.000000,501.000000,1.000000,127.352809,36.352871
75%,19.000000,10.000000,601.000000,2.000000,127.404663,36.748068
max,31.000000,10.000000,610.000000,3.000000,130.869092,127.105550

In [9]:
df_kp20.describe(include='object')

,RECV_DEPT_NM,RECV_CPLT_DM,HPPN_PNU_ADDR,SME_EVT_YN
count,77077,77077,47805,13442
unique,16,75271,28593,2
top,충남청,20/12/09 14:54:38.000000000,대전광역시 동구 판암동(판암1동) 458-6,Y
freq,41814,3,562,12902

In [10]:
df_kp21.shape

(2594060, 10)

In [11]:
df_kp21.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,대전청,21/03/07 00:00:01.000000000,13,10,604,3.0,대전광역시 서구 둔산동 1122,127.373676,36.350975,Y
1,대전청,21/03/07 00:02:13.000000000,13,10,201,1.0,대전광역시 유성구 상대동(원신흥동) 469-9,127.339018,36.347420,NaN
2,대전청,21/03/07 00:00:33.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
3,대전청,21/03/07 00:01:18.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
4,대전청,21/03/07 00:01:43.000000000,13,10,308,1.0,대전광역시 중구 선화동 141-16,127.420455,36.330413,NaN

In [12]:
df_kp21.tail()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
2594055,대전청,23/01/12 11:23:09.000000000,13,10,104,1.0,대전광역시 유성구 봉명동 (행정:원신흥동 ) 1016-7,127.344600,36.352272,NaN
2594056,충남청,23/01/16 11:59:47.000000000,19,10,307,2.0,충청남도 서산시 음암면 부장리(음암면 ) 560-4,126.514047,36.785626,NaN
2594057,충남청,23/01/16 11:58:54.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2594058,충남청,23/01/14 01:00:47.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2594059,대전청,23/01/14 01:22:31.000000000,13,10,606,1.0,NaN,127.404663,36.341685,NaN

In [13]:
df_kp21.describe()

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_X,HPPN_Y
count,2.594060e+06,2.594060e+06,2.594060e+06,2.570166e+06,1.899659e+06,1.899659e+06
mean,1.700251e+01,9.992336e+00,4.579272e+02,1.920799e+00,1.271893e+02,3.649330e+01
std,3.983839e+00,1.952455e-01,1.461437e+02,8.761132e-01,3.173263e-01,2.720425e-01
min,8.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,3.647666e+01,3.321955e+01
25%,1.300000e+01,1.000000e+01,3.070000e+02,1.000000e+00,1.270993e+02,3.634168e+01
50%,1.900000e+01,1.000000e+01,5.010000e+02,2.000000e+00,1.273364e+02,3.635569e+01
75%,1.900000e+01,1.000000e+01,6.010000e+02,3.000000e+00,1.274047e+02,3.677263e+01
max,3.100000e+01,1.000000e+01,6.100000e+02,3.000000e+00,1.308374e+02,1.272489e+02

In [14]:
df_kp21.describe(include='object')

,RECV_DEPT_NM,RECV_CPLT_DM,HPPN_PNU_ADDR,SME_EVT_YN
count,2594060,2594060,1521966,514937
unique,25,2516819,488370,2
top,충남청,22/09/04 04:41:51.000000000,전라북도 김제시 상동동(검산동) 536,Y
freq,1548809,9,12308,479386

## KP 데이터 병합

In [15]:
df_kp = pd.concat([df_kp20, df_kp21], ignore_index=True)
df_kp.shape

(2671137, 10)

In [16]:
df_kp20.shape[0] + df_kp21.shape[0]

2671137

In [17]:
df_kp

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN
...,...,...,...,...,...,...,...,...,...,...
2671132,대전청,23/01/12 11:23:09.000000000,13,10,104,1.0,대전광역시 유성구 봉명동 (행정:원신흥동 ) 1016-7,127.344600,36.352272,NaN
2671133,충남청,23/01/16 11:59:47.000000000,19,10,307,2.0,충청남도 서산시 음암면 부장리(음암면 ) 560-4,126.514047,36.785626,NaN
2671134,충남청,23/01/16 11:58:54.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2671135,충남청,23/01/14 01:00:47.000000000,19,10,601,3.0,NaN,NaN,NaN,NaN
2671136,대전청,23/01/14 01:22:31.000000000,13,10,606,1.0,NaN,127.404663,36.341685,NaN

### KP 데이터 파생변수

In [18]:
df_kp['RECV_CPLT_DM'][0]

'20/12/01 01:43:07.000000000'

In [19]:
df_kp['RECV_CPLT_DM'] = df_kp['RECV_CPLT_DM'].str.split('.').str[0]

In [20]:
df_kp['RECV_CPLT_DM'][0]

'20/12/01 01:43:07'

In [21]:
df_kp['RECV_CPLT_DM'] = pd.to_datetime(df_kp['RECV_CPLT_DM'], format="%y/%m/%d %H:%M:%S")

In [22]:
df_kp["RECV_CPLT_DM"].head(1)

0   2020-12-01 01:43:07
Name: RECV_CPLT_DM, dtype: datetime64[ns]

In [23]:
df_kp = df_kp.rename(columns={'HPPN_PNU_ADDR':'HPPN_ADDR'})

In [24]:
df_kp.head(1)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,2020-12-01 01:43:07,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y

## NPA 데이터

변수 정리
   
RECV_CPLT_DT : 접수 완료 날짜   
RECV_CPLT_TM : 접수 완료 시간   
NPA_CL : 경찰청 코드   
EVT_STAT_CD : 사건 상태 코드   
EVT_CL_CD : 사건 종별 코드   
RPTER_SEX : 신고자 성별   
HPPN_OLD_ADDR : 발생 주소   
HPPN_X : 위도   
HPPN_Y : 경도   
SME_EVT_YN : 동일 사건 여부

In [25]:
df_npa20.shape

(1178244, 10)

In [26]:
df_npa20.head()

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,20200101,7,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y
1,20200101,132,13,10,501,1,대전광역시 중구 대흥동(대흥동) 499-1,127.421295,36.325575,NaN
2,20200101,39,13,10,501,1,NaN,127.404663,36.341685,NaN
3,20200101,110,13,10,601,3,NaN,0.000000,0.000000,NaN
4,20200101,342,13,10,601,1,NaN,127.404663,36.341685,NaN

In [27]:
df_npa20["RECV_CPLT_TM"] = df_npa20["RECV_CPLT_TM"].astype('str')

In [28]:
df_npa20["RECV_CPLT_TM"] = df_npa20["RECV_CPLT_TM"].str.rjust(width=6, fillchar='0')

In [29]:
df_npa20.head(1)

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,20200101,000007,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.40927,36.33301,Y

In [30]:
df_npa20['RECV_CPLT_DM'] = df_npa20['RECV_CPLT_DT'].astype('str') + df_npa20['RECV_CPLT_TM'].astype('str')

In [31]:
df_npa20['RECV_CPLT_DM'] = pd.to_datetime(df_npa20['RECV_CPLT_DM'])

In [32]:
df_npa20['RECV_CPLT_DM'].head(1)

0   2020-01-01 00:00:07
Name: RECV_CPLT_DM, dtype: datetime64[ns]

In [33]:
df_npa20 = df_npa20.drop(labels=['RECV_CPLT_DT', 'RECV_CPLT_TM'], axis=1)

In [34]:
df_npa20['NPA_CL'].value_counts()

19    726251
13    451993
Name: NPA_CL, dtype: int64

In [35]:
df_npa20['RECV_DEPT_NM'] = ['대전청' if x == 13 else '충남청' for x in df_npa20['NPA_CL']]

In [36]:
df_npa20 = df_npa20.rename(columns={'HPPN_OLD_ADDR':'HPPN_ADDR'})

In [37]:
df_npa20.head(1)

,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN,RECV_CPLT_DM,RECV_DEPT_NM
0,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.40927,36.33301,Y,2020-01-01 00:00:07,대전청

In [38]:
df_npa20.shape

(1178244, 10)

In [39]:
df_kp.shape

(2671137, 10)

## KP, NPA 데이터 병합

In [40]:
df = pd.concat([df_kp, df_npa20], ignore_index=True)

In [41]:
df.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,2020-12-01 01:43:07,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,2020-12-01 02:05:04,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,2020-12-01 02:06:52,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,2020-12-01 02:37:25,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,2020-12-01 08:17:50,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN

In [42]:
df.shape

(3849381, 10)

In [43]:
df = df.drop_duplicates()

In [44]:
df.shape

(3846630, 10)

## 데이터 변환

In [45]:
codeBook = pd.read_excel('./data/codeBook_v3.xlsx')

In [46]:
codeBook.head()

   No     컬럼명   컬럼 그룹  코드명  코드값
0   1  NPA_CL  경찰청 구분   본청    1
1   2  NPA_CL  경찰청 구분  서울청    8
2   3  NPA_CL  경찰청 구분  부산청    9
3   4  NPA_CL  경찰청 구분  대구청   10
4   5  NPA_CL  경찰청 구분  인천청   11

### 경찰청 (NPA_CL)

In [47]:
npa_cl_code_dict = dict(zip(codeBook.loc[codeBook['컬럼명'] == 'NPA_CL']['코드값'].astype(str).tolist(), codeBook.loc[codeBook['컬럼명'] == 'NPA_CL']['코드명'].tolist()))

In [48]:
npa_cl_code_dict

{'1': '본청',
 '8': '서울청',
 '9': '부산청',
 '10': '대구청',
 '11': '인천청',
 '12': '광주청',
 '13': '대전청',
 '14': '울산청',
 '15': '경기남부청',
 '16': '경기북부청',
 '17': '강원청',
 '18': '충북청',
 '19': '충남청',
 '20': '전북청',
 '21': '전남청',
 '22': '경북청',
 '23': '경남청',
 '24': '제주청',
 '31': '세종청'}

In [49]:
df['NPA_CL'] = df['NPA_CL'].astype('str').map(npa_cl_code_dict)

In [50]:
df['NPA_CL'].value_counts()

충남청      2203874
대전청      1517026
세종청        95746
경기남부청       7810
충북청         6395
서울청         5347
전북청         3039
인천청         1215
전남청          998
경기북부청        908
경북청          865
부산청          685
경남청          652
강원청          612
대구청          543
광주청          458
제주청          259
울산청          198
Name: NPA_CL, dtype: int64

### 사건상태코드 (EVT_STAT_CD)

In [51]:
evt_stat_code_dict = dict(zip(codeBook.loc[codeBook['컬럼명'] == 'EVT_STAT_CD']['코드값'].astype(str).tolist(), codeBook.loc[codeBook['컬럼명'] == 'EVT_STAT_CD']['코드명'].tolist()))

In [52]:
evt_stat_code_dict

{'1': '접수중',
 '2': '접수',
 '3': '초기지령',
 '4': '지령',
 '5': '도착',
 '6': '네비종결',
 '7': '종결요청',
 '8': '지령취소',
 '9': '타청이첩',
 '10': '종결요청'}

In [53]:
df['EVT_STAT_CD'] = df['EVT_STAT_CD'].astype('str').map(evt_stat_code_dict)

In [54]:
df.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,2020-12-01 01:43:07,충남청,종결요청,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,2020-12-01 02:05:04,대전청,종결요청,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,2020-12-01 02:06:52,대전청,종결요청,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,2020-12-01 02:37:25,충남청,종결요청,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,2020-12-01 08:17:50,충남청,종결요청,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN

### 사건종별코드 (EVT_CL_CD)

In [55]:
evt_cl_code_dict = dict(zip(codeBook.loc[codeBook['컬럼명'] == 'EVT_CL_CD']['코드값'].astype(str).tolist(), codeBook.loc[codeBook['컬럼명'] == 'EVT_CL_CD']['코드명'].tolist()))

In [56]:
evt_cl_code_dict

{'1': '중요범죄',
 '2': '기타범죄',
 '3': '질서유지',
 '4': '교통',
 '5': '기타경찰업무',
 '6': '타기관_기타',
 '101': '살인',
 '102': '강도',
 '103': '치기',
 '104': '절도',
 '105': '납치감금',
 '106': '성폭력',
 '107': '가정폭력',
 '108': '아동학대(가정내)',
 '109': '아동학대(기타)',
 '201': '폭력',
 '202': '사기',
 '203': '공갈',
 '204': '협박',
 '205': '도박',
 '206': '재물손괴',
 '207': '주거침입',
 '208': '풍속영업',
 '209': '수배불심자',
 '210': '기타형사범',
 '211': '데이트폭력',
 '212': '스토킹',
 '213': '학교폭력',
 '214': '마약',
 '215': '보이스피싱',
 '216': '동물학대',
 '301': '시비',
 '302': '행패소란',
 '303': '청소년비행',
 '304': '무전취식승차',
 '305': '주취자',
 '306': '보호조치',
 '307': '위험방지',
 '308': '기타경범',
 '401': '교통사고',
 '402': '교통불편',
 '403': '교통위반',
 '404': '사망.대형사고',
 '405': '인피도주',
 '406': '음주운전',
 '501': '상담문의',
 '502': '변사자',
 '503': '비상벨',
 '504': '경비업체요청',
 '505': '가출 등',
 '506': '분실습득',
 '507': 'FTX',
 '508': '자살',
 '509': '실종(실종아동 등)',
 '601': '내용확인불가',
 '602': '화재',
 '603': '구조요청',
 '604': '소음',
 '605': '노점상',
 '606': '기타_타기관',
 '607': '서비스요청',
 '608': '청탁금지법',
 '609': '재해재난',
 '610': '위험동물'}

In [57]:
df['EVT_CL_CD'] = df['EVT_CL_CD'].astype('str').map(evt_cl_code_dict)

In [58]:
df['EVT_CL_CD'].value_counts()

내용확인불가        1224272
상담문의           757112
위험방지           273019
교통사고           264362
시비             119017
기타형사범           93384
폭력              92858
행패소란            91450
소음              75854
음주운전            70072
주취자             66892
교통불편            60095
보호조치            59562
기타_타기관          59058
절도              54870
분실습득            48630
보이스피싱           46268
가정폭력            45604
교통위반            35897
비상벨             32121
실종(실종아동 등)      31547
자살              24708
청소년비행           20024
재물손괴            18168
기타경범            16932
무전취식승차          16749
풍속영업            15274
데이트폭력           14784
도박              13500
사기              12871
가출 등            12108
재해재난            10512
화재               8914
변사자              7426
서비스요청            6973
수배불심자            6594
구조요청             6011
아동학대(가정내)        5784
성폭력              4648
주거침입             3929
FTX              3883
스토킹              3294
위험동물             2481
학교폭력             2337
협박               2246
아동학대(기타)         1003
동물학대              882
마약                843
경비업체요청            667
납치감금              624
살인                123
공갈                105
강도                100
노점상                92
인피도주               52
사망.대형사고            23
치기                 21
청탁금지법               1
Name: EVT_CL_CD, dtype: int64

### 성별 (RPTER_SEX)

In [59]:
def sex_sub(n):
    if n == 1:
        return '남성'
    elif n == 2:
        return '여성'
    else:
        return '불상'

In [60]:
df['RPTER_SEX'] = df['RPTER_SEX'].map(sex_sub)

In [61]:
df['RPTER_SEX'].value_counts()

불상    2111843
남성    1133460
여성     601327
Name: RPTER_SEX, dtype: int64

## 컬럼명 변경

In [62]:
df.columns

Index(['RECV_DEPT_NM', 'RECV_CPLT_DM', 'NPA_CL', 'EVT_STAT_CD', 'EVT_CL_CD',
       'RPTER_SEX', 'HPPN_ADDR', 'HPPN_X', 'HPPN_Y', 'SME_EVT_YN'],
      dtype='object')

In [63]:
df.columns = ['접수부서', '접수완료일시', '경찰청구분', '사건상태', '사건종류', '신고자 성별', '발생지점', '발생지 위도', '발생지 경도', '동일사건여부']

In [64]:
df.head()

,접수부서,접수완료일시,경찰청구분,사건상태,사건종류,신고자 성별,발생지점,발생지 위도,발생지 경도,동일사건여부
0,충남청,2020-12-01 01:43:07,충남청,종결요청,주취자,남성,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,2020-12-01 02:05:04,대전청,종결요청,내용확인불가,불상,NaN,127.404663,36.341685,NaN
2,대전청,2020-12-01 02:06:52,대전청,종결요청,내용확인불가,남성,NaN,127.404663,36.341685,NaN
3,충남청,2020-12-01 02:37:25,충남청,종결요청,기타_타기관,불상,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,2020-12-01 08:17:50,충남청,종결요청,교통사고,여성,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN

## 파생변수

In [65]:
df["Year"] = df["접수완료일시"].dt.year
df["Month"] = df["접수완료일시"].dt.month
df['Year Month'] = df['접수완료일시'].map(lambda x : str(x)[:7])
df["Day of Week"] = df["접수완료일시"].dt.day_name()
df["Hour"] = df["접수완료일시"].dt.hour
df['일자'] = df['접수완료일시'].dt.date

In [66]:
df.head()

,접수부서,접수완료일시,경찰청구분,사건상태,사건종류,신고자 성별,발생지점,발생지 위도,발생지 경도,동일사건여부,Year,Month,Year Month,Day of Week,Hour,일자
0,충남청,2020-12-01 01:43:07,충남청,종결요청,주취자,남성,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y,2020,12,2020-12,Tuesday,1,2020-12-01
1,대전청,2020-12-01 02:05:04,대전청,종결요청,내용확인불가,불상,NaN,127.404663,36.341685,NaN,2020,12,2020-12,Tuesday,2,2020-12-01
2,대전청,2020-12-01 02:06:52,대전청,종결요청,내용확인불가,남성,NaN,127.404663,36.341685,NaN,2020,12,2020-12,Tuesday,2,2020-12-01
3,충남청,2020-12-01 02:37:25,충남청,종결요청,기타_타기관,불상,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N,2020,12,2020-12,Tuesday,2,2020-12-01
4,충남청,2020-12-01 08:17:50,충남청,종결요청,교통사고,여성,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN,2020,12,2020-12,Tuesday,8,2020-12-01

In [67]:
df = df.rename(columns={'Year' : '연도', 'Month' : '월', 'Year Month' : '연월', 'Day of Week' : '요일', 'Hour' : '시간대'})

In [68]:
df

,접수부서,접수완료일시,경찰청구분,사건상태,사건종류,신고자 성별,발생지점,발생지 위도,발생지 경도,동일사건여부,연도,월,연월,요일,시간대,일자
0,충남청,2020-12-01 01:43:07,충남청,종결요청,주취자,남성,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y,2020,12,2020-12,Tuesday,1,2020-12-01
1,대전청,2020-12-01 02:05:04,대전청,종결요청,내용확인불가,불상,NaN,127.404663,36.341685,NaN,2020,12,2020-12,Tuesday,2,2020-12-01
2,대전청,2020-12-01 02:06:52,대전청,종결요청,내용확인불가,남성,NaN,127.404663,36.341685,NaN,2020,12,2020-12,Tuesday,2,2020-12-01
3,충남청,2020-12-01 02:37:25,충남청,종결요청,기타_타기관,불상,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N,2020,12,2020-12,Tuesday,2,2020-12-01
4,충남청,2020-12-01 08:17:50,충남청,종결요청,교통사고,여성,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN,2020,12,2020-12,Tuesday,8,2020-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3849376,충남청,2020-11-22 00:35:05,충남청,종결요청,상담문의,불상,,NaN,NaN,,2020,11,2020-11,Sunday,0,2020-11-22
3849377,대전청,2020-11-22 00:52:13,대전청,종결요청,내용확인불가,불상,,127.404663,36.341685,,2020,11,2020-11,Sunday,0,2020-11-22
3849378,충남청,2020-11-22 00:46:27,충남청,종결요청,내용확인불가,불상,,NaN,NaN,Y,2020,11,2020-11,Sunday,0,2020-11-22
3849379,충남청,2020-11-22 00:52:46,충남청,도착,시비,불상,충청남도 보령시 신흑동(행정:대천5동),126.516040,36.305619,,2020,11,2020-11,Sunday,0,2020-11-22
3849380,대전청,2020-11-22 00:11:34,대전청,종결요청,내용확인불가,불상,,127.404663,36.341685,,2020,11,2020-11,Sunday,0,2020-11-22

In [69]:
df = df.sort_values('접수완료일시')

In [70]:
df['접수부서'].value_counts()

충남청         2314818
대전청         1515583
대전역지구대         2516
남대전지구대         2182
서대전지구대         1865
대전중부서          1278
대전동부서          1177
대전유성서          1101
세종로파출소          966
대전대덕서           804
대전둔산서           787
대전서부서           784
세종대왕파출소         341
대전파출소           317
대전동부            270
대전중부            270
대전둔산            245
대전유성            209
대전대덕            194
세종청             186
세종남부서           166
세종서             164
대전서부            155
2지구대(충남)         95
세종북부서            80
세종               77
Name: 접수부서, dtype: int64

In [71]:
def dept_replace(x):
    if '대전' in x:
        return '대전청'
    elif '세종' in x:
        return '세종청'
    else:
        return '충남청'

In [72]:
df['접수부서'] = df['접수부서'].map(dept_replace)

In [73]:
df.head()

,접수부서,접수완료일시,경찰청구분,사건상태,사건종류,신고자 성별,발생지점,발생지 위도,발생지 경도,동일사건여부,연도,월,연월,요일,시간대,일자
2671137,대전청,2020-01-01 00:00:07,대전청,종결요청,상담문의,불상,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y,2020,1,2020-01,Wednesday,0,2020-01-01
2673005,충남청,2020-01-01 00:00:08,충남청,종결요청,자살,불상,충청북도 청주시 흥덕구 비하동(행정:강서1동) 300,127.420740,36.640520,Y,2020,1,2020-01,Wednesday,0,2020-01-01
2673004,충남청,2020-01-01 00:00:29,충남청,종결요청,무전취식승차,불상,충청남도 당진시 대덕동(행정:당진2동) 1442,126.631965,36.886277,NaN,2020,1,2020-01,Wednesday,0,2020-01-01
2671139,대전청,2020-01-01 00:00:39,대전청,종결요청,상담문의,불상,NaN,127.404663,36.341685,NaN,2020,1,2020-01,Wednesday,0,2020-01-01
2673003,충남청,2020-01-01 00:00:51,충남청,종결요청,폭력,불상,충청남도 당진시 송악읍 기지시리(송악읍) 510,126.695258,36.900175,NaN,2020,1,2020-01,Wednesday,0,2020-01-01

In [74]:
df['접수부서'].value_counts()

충남청    2314913
대전청    1529737
세종청       1980
Name: 접수부서, dtype: int64

In [75]:
dayofweek_dict = {'Monday' : '월',
                  'Tuesday' : '화',
                  'Wednesday' : '수',
                  'Thursday' : '목',
                  'Friday' : '금',
                  'Saturday' : '토',
                  'Sunday' : '일'
                  }

In [76]:
df['요일'] = df['요일'].map(dayofweek_dict)

In [77]:
df['요일'].value_counts()

토    591266
금    573578
수    544102
목    542900
월    534704
화    534621
일    525459
Name: 요일, dtype: int64

# 데이터 내보내기

In [78]:
file_name = 'police_data.csv'

In [79]:
df.to_csv(f'{file_path}{file_name}', index=False)

In [80]:
check = pd.read_csv(f'{file_path}{file_name}')
check.head()

,접수부서,접수완료일시,경찰청구분,사건상태,사건종류,신고자 성별,발생지점,발생지 위도,발생지 경도,동일사건여부,연도,월,연월,요일,시간대,일자
0,대전청,2020-01-01 00:00:07,대전청,종결요청,상담문의,불상,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y,2020,1,2020-01,수,0,2020-01-01
1,충남청,2020-01-01 00:00:08,충남청,종결요청,자살,불상,충청북도 청주시 흥덕구 비하동(행정:강서1동) 300,127.420740,36.640520,Y,2020,1,2020-01,수,0,2020-01-01
2,충남청,2020-01-01 00:00:29,충남청,종결요청,무전취식승차,불상,충청남도 당진시 대덕동(행정:당진2동) 1442,126.631965,36.886277,NaN,2020,1,2020-01,수,0,2020-01-01
3,대전청,2020-01-01 00:00:39,대전청,종결요청,상담문의,불상,NaN,127.404663,36.341685,NaN,2020,1,2020-01,수,0,2020-01-01
4,충남청,2020-01-01 00:00:51,충남청,종결요청,폭력,불상,충청남도 당진시 송악읍 기지시리(송악읍) 510,126.695258,36.900175,NaN,2020,1,2020-01,수,0,2020-01-01